/**
 * DATA.JS
 * Contains: Translations, Configuration, Constants
 * Load this file BEFORE script.js in your HTML.
 */

const EXCEL_FILE = 'DB.xlsx';

const COL_MAP_DB = {
    'PN': 'P/N', 'Status': 'Status', 'LTB': 'LTB', 'size': 'Size', 'Resolution': 'Resolution',
    'Type': 'Touch Type', 'CPU': 'CPU', 'Memory': 'Memory supported', 'APPLICATION': 'APPLICATION',
    'MARKET': 'MARKET', 'ExtraApp': 'EXTRAAPPLICATION', 'Comment': 'COMMENT', 'Series': 'PRODUCT SERIES',
    'ManualLink': 'DatasheetLink', 'DirectLink': 'DirectLink', 'ThreeDLink': '3DLINK',
    'TechLink': 'TECHINCALLINKS', 'AvailLink': 'Availability', 'Suggested': 'SUGGESTED PRODUCT'
};

const EXCLUSIONS = ["n/a", "-", "na", "", "configuration submitted successfully!", "undefined", "0", "a"];
const HISTORY_KEY = 'mya_search_history';
const SESSION_KEY = 'advantech_portal_session_v1';
const LANG_KEY = 'advantech_lang_v1';

const MODULAR_BOX_PCS = [
    "TPC-B300-J20A", "TPC-B300-E20A", "TPC-B520-D50A", "TPC-B520-D70A", "TPC-B520L-C30A",
    "TPC-B510-833BE", "TPC-B510-853BE", "TPC-B510-873BE", "TPC-B500-6C2AE", "TPC-B610H-A00A", "TPC-B610W-A00A"
];

const TARGET_CERTIFICATIONS = ["C1/D2", "IECEx/ATEX Zone 2/22", "CCC", "UL"];
const TARGET_OS = ["Win 10", "Win 11", "Android", "Linux"];
const MONITOR_ALLOWED_OPTIONAL = ['series', 'MARKET', 'APPLICATION', 'Certifications', 'ltb', 'Resolution'];

// --- TRANSLATION DICTIONARY ---
const TRANSLATIONS = {
    'EN': { name:'English', dir:'ltr', labels: {'APPLICATION':'APPLICATION','Type':'Touch Technology','Memory':'Min Memory','size':'Screen Size','OS Support':'Operating System','Mounting':'Mounting Options','MARKET':'MARKET','Series':'Product Series','CPU':'CPU','Certifications':'Certifications','Status':'Status','PN':'P/N','LTB':'LTB','Resolution':'Resolution','Touch':'Touch','Actions':'Actions','Search':'Search P/N...','Back':'Back','Customize':'Customize Filters','SelectAll':'Select All','None':'None','Selected':'Selected','NoResults':'No results found.','LoginTitle':'HMI Product Configurator','LoginBtn':'Login via MYA','Skip':'Skip','Verify':'Continue','Support':'Support','Datasheet':'Datasheet','Contact':'Contact PSM','Report':'Report Issue','Close':'Close'} },
    'IT': { name:'Italiano', dir:'ltr', labels: {'APPLICATION':'APPLICAZIONE','Type':'Tecnologia Touch','Memory':'Memoria Min','size':'Dimensione','OS Support':'Sistema Operativo','Mounting':'Montaggio','MARKET':'MERCATO','Series':'Serie Prodotto','CPU':'CPU','Certifications':'Certificazioni','Status':'Stato','PN':'Codice (P/N)','LTB':'Fine Vita (LTB)','Resolution':'Risoluzione','Touch':'Touch','Actions':'Azioni','Search':'Cerca P/N...','Back':'Indietro','Customize':'Filtri','SelectAll':'Seleziona Tutti','None':'Nessuno','Selected':'Selezionati','NoResults':'Nessun risultato trovato.','LoginTitle':'Selettore Prodotti HMI','LoginBtn':'Accedi via MYA','Skip':'Salta','Verify':'Continua','Support':'Supporto','Datasheet':'Scheda Tecnica','Contact':'Contatta PSM','Report':'Segnala Errore','Close':'Chiudi'} },
    'ES': { name:'Español', dir:'ltr', labels: {'APPLICATION':'APLICACIÓN','Type':'Tecnología Táctil','Memory':'Memoria Mín','size':'Tamaño Pantalla','OS Support':'Sistema Operativo','Mounting':'Montaje','MARKET':'MERCADO','Series':'Serie Producto','CPU':'CPU','Certifications':'Certificaciones','Status':'Estado','PN':'N/P','LTB':'LTB','Resolution':'Resolución','Touch':'Táctil','Actions':'Acciones','Search':'Buscar P/N...','Back':'Atrás','Customize':'Filtros','SelectAll':'Sel. Todos','None':'Ninguno','Selected':'Seleccionados','NoResults':'No se encontraron resultados.','LoginTitle':'Portal Configuración HMI','LoginBtn':'Entrar vía MYA','Skip':'Omitir','Verify':'Continuar','Support':'Soporte','Datasheet':'Ficha Técnica','Contact':'Contactar PSM','Report':'Reportar Error','Close':'Cerrar'} },
    'FR': { name:'Français', dir:'ltr', labels: {'APPLICATION':'APPLICATION','Type':'Technologie Tactile','Memory':'Mémoire Min','size':'Taille Écran','OS Support':'Système Expl.','Mounting':'Montage','MARKET':'MARCHÉ','Series':'Série Produit','CPU':'CPU','Certifications':'Certifications','Status':'Statut','PN':'P/N','LTB':'LTB','Resolution':'Résolution','Touch':'Tactile','Actions':'Actions','Search':'Rechercher P/N...','Back':'Retour','Customize':'Filtres','SelectAll':'Tout Sélect.','None':'Aucun','Selected':'Sélectionnés','NoResults':'Aucun résultat trouvé.','LoginTitle':'Portail Config. HMI','LoginBtn':'Connexion MYA','Skip':'Passer','Verify':'Continuer','Support':'Support','Datasheet':'Fiche Technique','Contact':'Contacter PSM','Report':'Signaler Bug','Close':'Fermer'} },
    'DE': { name:'Deutsch', dir:'ltr', labels: {'APPLICATION':'ANWENDUNG','Type':'Touch-Technologie','Memory':'Min. Speicher','size':'Bildschirmgröße','OS Support':'Betriebssystem','Mounting':'Montage','MARKET':'MARKT','Series':'Produktserie','CPU':'CPU','Certifications':'Zertifizierungen','Status':'Status','PN':'Teilenr.','LTB':'LTB','Resolution':'Auflösung','Touch':'Touch','Actions':'Aktionen','Search':'Suche P/N...','Back':'Zurück','Customize':'Filter','SelectAll':'Alle Auswählen','None':'Keine','Selected':'Ausgewählt','NoResults':'Keine Ergebnisse gefunden.','LoginTitle':'HMI Konfigurationsportal','LoginBtn':'Login über MYA','Skip':'Überspringen','Verify':'Weiter','Support':'Support','Datasheet':'Datenblatt','Contact':'PSM Kontaktieren','Report':'Fehler Melden','Close':'Schließen'} },
    'PT': { name:'Português', dir:'ltr', labels: {'APPLICATION':'APLICAÇÃO','Type':'Tecnologia Tátil','Memory':'Memória Mín','size':'Tamanho Ecrã','OS Support':'Sistema Operativo','Mounting':'Montagem','MARKET':'MERCADO','Series':'Série Produto','CPU':'CPU','Certifications':'Certificações','Status':'Estado','PN':'P/N','LTB':'LTB','Resolution':'Resolução','Touch':'Tátil','Actions':'Ações','Search':'Pesquisar P/N...','Back':'Voltar','Customize':'Filtros','SelectAll':'Sel. Todos','None':'Nenhum','Selected':'Selecionados','NoResults':'Nenhum resultado encontrado.','LoginTitle':'Portal Configuração HMI','LoginBtn':'Login via MYA','Skip':'Pular','Verify':'Continuar','Support':'Suporte','Datasheet':'Ficha Técnica','Contact':'Contatar PSM','Report':'Reportar Erro','Close':'Fechar'} },
    'NL': { name:'Nederlands', dir:'ltr', labels: {'APPLICATION':'TOEPASSING','Type':'Touch Technologie','Memory':'Min Geheugen','size':'Schermgrootte','OS Support':'Besturingssysteem','Mounting':'Montage','MARKET':'MARKT','Series':'Productserie','CPU':'CPU','Certifications':'Certificeringen','Status':'Status','PN':'Onderdeelnr.','LTB':'LTB','Resolution':'Resolutie','Touch':'Touch','Actions':'Acties','Search':'Zoeken P/N...','Back':'Terug','Customize':'Filters','SelectAll':'Alles Selecteren','None':'Geen','Selected':'Geselecteerd','NoResults':'Geen resultaten gevonden.','LoginTitle':'HMI Configuratie Portaal','LoginBtn':'Login via MYA','Skip':'Overslaan','Verify':'Doorgaan','Support':'Ondersteuning','Datasheet':'Datasheet','Contact':'Contacteer PSM','Report':'Meld Probleem','Close':'Sluiten'} },
    'GR': { name:'Ελληνικά', dir:'ltr', labels: {'APPLICATION':'ΕΦΑΡΜΟΓΗ','Type':'Τεχνολογία Αφής','Memory':'Μνήμη','size':'Μέγεθος Οθόνης','OS Support':'Λειτ. Σύστημα','Mounting':'Τοποθέτηση','MARKET':'ΑΓΟΡΑ','Series':'Σειρά','CPU':'CPU','Certifications':'Πιστοποιήσεις','Status':'Κατάσταση','PN':'Κωδικός','LTB':'LTB','Resolution':'Ανάλυση','Touch':'Αφή','Actions':'Ενέργειες','Search':'Αναζήτηση...','Back':'Πίσω','Customize':'Φίλτρα','SelectAll':'Επιλογή Όλων','None':'Κανένα','Selected':'Επιλεγμένα','NoResults':'Δεν βρέθηκαν αποτελέσματα.','LoginTitle':'Πύλη Διαμόρφωσης HMI','LoginBtn':'Σύνδεση MYA','Skip':'Παράλειψη','Verify':'Συνέχεια','Support':'Υποστήριξη','Datasheet':'Φύλλο Δεδομένων','Contact':'Επικοινωνία PSM','Report':'Αναφορά','Close':'Κλείσιμο'} },
    'JA': { name:'日本語', dir:'ltr', labels: {'APPLICATION':'応用','Type':'タッチ技術','Memory':'メモリ','size':'画面サイズ','OS Support':'OS','Mounting':'取り付け','MARKET':'市場','Series':'製品シリーズ','CPU':'CPU','Certifications':'認証','Status':'状態','PN':'品番','LTB':'販売終了','Resolution':'解像度','Touch':'タッチ','Actions':'アクション','Search':'品番検索...','Back':'戻る','Customize':'フィルター','SelectAll':'すべて選択','None':'なし','Selected':'選択中','NoResults':'結果が見つかりませんでした。','LoginTitle':'HMI構成ポータル','LoginBtn':'MYAでログイン','Skip':'スキップ','Verify':'続行','Support':'サポート','Datasheet':'データシート','Contact':'PSMへ連絡','Report':'問題を報告','Close':'閉じる'} },
    'ZH': { name:'繁體中文', dir:'ltr', labels: {'APPLICATION':'應用','Type':'觸控技術','Memory':'記憶體','size':'螢幕尺寸','OS Support':'作業系統','Mounting':'安裝方式','MARKET':'市場','Series':'產品系列','CPU':'CPU','Certifications':'認證','Status':'狀態','PN':'料號','LTB':'最後下單日','Resolution':'解析度','Touch':'觸控','Actions':'操作','Search':'搜尋料號...','Back':'返回','Customize':'篩選器','SelectAll':'全選','None':'無','Selected':'已選','NoResults':'未找到結果。','LoginTitle':'HMI 配置門戶','LoginBtn':'MYA 登錄','Skip':'跳過','Verify':'繼續','Support':'支援','Datasheet':'規格書','Contact':'聯繫 PSM','Report':'回報問題','Close':'關閉'} },'PL': { name:'Polski', dir:'ltr', labels: {'APPLICATION':'APLIKACJA','Type':'Technologia Dotyku','Memory':'Min. Pamięć','size':'Rozmiar Ekranu','OS Support':'System Operacyjny','Mounting':'Montaż','MARKET':'RYNEK','Series':'Seria Produktu','CPU':'CPU','Certifications':'Certyfikaty','Status':'Status','PN':'Nr Części','LTB':'LTB','Resolution':'Rozdzielczość','Touch':'Dotyk','Actions':'Akcje','Search':'Szukaj P/N...','Back':'Wstecz','Customize':'Filtry','SelectAll':'Wybierz Wszystkie','None':'Brak','Selected':'Wybrano','NoResults':'Brak wyników.','LoginTitle':'Konfigurator HMI','LoginBtn':'Zaloguj przez MYA','Skip':'Pomiń','Verify':'Kontynuuj','Support':'Wsparcie','Datasheet':'Karta Katalogowa','Contact':'Kontakt PSM','Report':'Zgłoś Błąd','Close':'Zamknij'} },
    'CZ': { name:'Čeština', dir:'ltr', labels: {'APPLICATION':'APLIKACE','Type':'Dotyková Tech.','Memory':'Min. Paměť','size':'Velikost Displeje','OS Support':'Operační Systém','Mounting':'Montáž','MARKET':'TRH','Series':'Produktová Řada','CPU':'CPU','Certifications':'Certifikace','Status':'Stav','PN':'Číslo Dílu','LTB':'LTB','Resolution':'Rozlišení','Touch':'Dotyk','Actions':'Akce','Search':'Hledat P/N...','Back':'Zpět','Customize':'Filtry','SelectAll':'Vybrat Vše','None':'Žádné','Selected':'Vybráno','NoResults':'Žádné výsledky.','LoginTitle':'Konfigurátor HMI','LoginBtn':'Přihlásit přes MYA','Skip':'Přeskočit','Verify':'Pokračovat','Support':'Podpora','Datasheet':'Datový List','Contact':'Kontaktovat PSM','Report':'Nahlásit Chybu','Close':'Zavřít'} },
    'SE': { name:'Svenska', dir:'ltr', labels: {'APPLICATION':'APPLIKATION','Type':'Touch-teknik','Memory':'Minne','size':'Skärmstorlek','OS Support':'Operativsystem','Mounting':'Montering','MARKET':'MARKNAD','Series':'Produktserie','CPU':'CPU','Certifications':'Certifieringar','Status':'Status','PN':'Art.nr','LTB':'LTB','Resolution':'Upplösning','Touch':'Touch','Actions':'Åtgärder','Search':'Sök P/N...','Back':'Tillbaka','Customize':'Filter','SelectAll':'Välj Alla','None':'Inga','Selected':'Valda','NoResults':'Inga resultat.','LoginTitle':'HMI Konfigurator','LoginBtn':'Logga in via MYA','Skip':'Hoppa över','Verify':'Fortsätt','Support':'Support','Datasheet':'Datablad','Contact':'Kontakta PSM','Report':'Rapportera Fel','Close':'Stäng'} },
    'AR': { name:'العربية', dir:'rtl', labels: {'APPLICATION':'التطبيق','Type':'تقنية اللمس','Memory':'الذاكرة','size':'حجم الشاشة','OS Support':'نظام التشغيل','Mounting':'التركيب','MARKET':'السوق','Series':'سلسلة المنتج','CPU':'المعالج','Certifications':'الشهادات','Status':'الحالة','PN':'رقم الجزء','LTB':'آخر طلب','Resolution':'الدقة','Touch':'لمس','Actions':'إجراءات','Search':'بحث...','Back':'رجوع','Customize':'تصفية','SelectAll':'تحديد الكل','None':'لا شيء','Selected':'محدد','NoResults':'لم يتم العثور على نتائج.','LoginTitle':'بوابة تكوين HMI','LoginBtn':'دخول عبر MYA','Skip':'تخطي','Verify':'متابعة','Support':'دعم','Datasheet':'ورقة البيانات','Contact':'اتصل بـ PSM','Report':'إبلاغ عن خطأ','Close':'إغلاق'} }
};